#! /bin/bash

set -e

PYS=$(py3versions -s)

cp -a debian/run_tests pytest.ini tests "$AUTOPKGTEST_TMP"
ROOTDIR=$(pwd)

cd "$AUTOPKGTEST_TMP"

for py in $PYS
do
    echo "Testing with $py:"
    ./run_tests $ROOTDIR/debian/get_test_exclusions $py -m pytest
done
